<?php


//站长微博系统配置文件
//Created: Oct 11, 2011, 14:04
return array (
	'R_DEF_MOD' => 'pub',
	'XT_IS_INIT' => 'false',
	'XT_USER_ID' => '',
	'XT_USER_NICK' => '',
	'XT_USER_PID' => '',
	'XT_USER_SPID' => '',
	'XT_VANCL_NICK' => '',
	'XT_SITE_DOMAIN' => '',
	'XT_PIWIK_ID' => '',
	'XT_IS_DIRECT' => 'true',
	'XT_IS_LOGIN' => 'false',
	'XT_IS_POST' => 'false',
	'XT_SIDS' => '',
	'XT_SHOPS' => '',
	'XT_CIDS' => '',
	'XT_APPSTORE' => '',
	'WB_QQ_AKEY' => '',
	'WB_QQ_SKEY' => '',
	'WB_QQ_UID' => '',
	'WB_QQ_NAME' => '',
	'WB_QQ_NICK' => '',
	'WB_QQ_USER_OAUTH_TOKEN' => '',
	'WB_QQ_USER_OAUTH_TOKEN_SECRET' => '',
	'WB_SOHU_AKEY' => '',
	'WB_SOHU_SKEY' => '',
	'WB_SOHU_UID' => '',
	'WB_SOHU_NAME' => '',
	'WB_SOHU_NICK' => '',
	'WB_SOHU_USER_OAUTH_TOKEN' => '',
	'WB_SOHU_USER_OAUTH_TOKEN_SECRET' => '',
	'WB_WY_AKEY' => '',
	'WB_WY_SKEY' => '',
	'WB_WY_UID' => '',
	'WB_WY_NAME' => '',
	'WB_WY_NICK' => '',
	'WB_WY_USER_OAUTH_TOKEN' => '',
	'WB_WY_USER_OAUTH_TOKEN_SECRET' => '',
	'WB_AKEY' => '',
	'WB_SKEY' => '',
	'SYSTEM_SINA_UID' => '',
	'SYSTEM_SINA_USERNAME' => '',
	'SYSTEM_SINA_USERNICK' => '',
	'V2_ACCESS_TOKEN' => '',
	'V2_REFRESH_TOKEN' => '',
	'WB_USER_OAUTH_TOKEN' => '',
	'WB_USER_OAUTH_TOKEN_SECRET' => '',
	'WB_USER_SITENAME' => '',
	'WB_USER_SITEINFO' => '',
	'WB_USER_NAME' => '',
	'WB_USER_EMAIL' => '',
	'WB_USER_QQ' => '',
	'WB_USER_MSN' => '',
	'WB_USER_TEL' => ''
);
?>