var HelpIndex = [
[".body file", "source/src/work/tmplbody.htm"], 
[".cwtpl file", "source/src/work/tmplscheme.htm"], 
["About chm2web", "source/src/intro.htm"], 
["Command Line", "source/src/work/cmdline.htm"], 
["Decompilation", "source/src/work/decomp.htm"], 
["features", "source/src/features.htm"], 
["frames version", "source/src/work/params.htm"], 
["Licensing Issues", "source/src/register/register.htm"], 
["Microsoft HTML Help Workshop", "source/src/hoto/createhelp.htm"], 
["mobile version", "source/src/work/params.htm"], 
["noframes version", "source/src/work/params.htm"], 
["pocket icon", "source/src/products.htm"], 
["Pre-processing", "source/src/work/convoptions/pageprep.htm"], 
["preset", "source/src/work/convoptions/pageprep.htm"], 
["projects", "source/src/work/projects.htm"], 
["Purchase", "source/src/register/register.htm"], 
["Register", [
["Why Should I Register?", "source/src/register/whyreg.htm"], 
["Purchasing and Licensing Issues", "source/src/register/register.htm"]]], 
["regular expression", "source/src/work/regexpr.htm"], 
["smart worktime tracker", "source/src/products.htm"], 
["Support", "source/src/about/techsup.htm"], 
["System Requirements", "source/src/sysreq.htm"], 
["Template Body", "source/src/work/tmplbody.htm"], 
["Template Scheme", "source/src/work/tmplscheme.htm"], 
["Templates", "source/src/work/templates.htm"], 
["timefix", "source/src/products.htm"], 
["Updates", "source/src/about/progupd.htm"], 
["Using chm2web", "source/src/work/work.htm"]];
